baseURL = "https://example.com"
languageCode = "en-us"
title = "Aleksei"
theme="archie"
copyright = "Â© Al"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	useCDN=false
	subtitle = "My personal blog and CV"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/freakeye"

[[params.social]]
name = "Telegram"
icon = "tg"
url = "https://t.me/amatesy"

# [[params.social]]
# name = "GitLab"
# icon = "gitlab"
# url = "https://gitlab.com/athul/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
